files: [
 {
  "source" : "/lib/l10n/intl_en.arb",
  "translation" : "/lib/l10n/intl_%two_letters_code%.arb",
  "type" : "arb",
 }
]
"project_id": "568557"
"api_token": "382c40ea7995b4778d45971a0d00ce6717e79f280f4d2afa4652a69eeea687035f5668ceb6e7c61c"

"preserve_hierarchy": true