name: Create GitHub Release
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      is_draft:
        description: "Mark as draft"
        required: true
        default: true
        type: boolean

# Declare default permissions as read only.
permissions: read-all

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Create build directory
        run: mkdir -p /tmp/build

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
        id: extract_branch
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Copy files to build directory
        run: |
          mkdir -p /tmp/build
          cp -R . /tmp/build

      - name: Set FLUTTER_ROOT environment variable and build dir
        run: echo "FLUTTER_ROOT=/tmp/build/flutter/bin" >> $GITHUB_ENV

      - run: $FLUTTER_ROOT/flutter doctor -v

      - name: Setup signing config
        uses: ./.github/actions/setup-android-signing-config
        with:
          keystore-key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          keystore-key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          keystore-store-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          release-keystore: ${{ secrets.RELEASE_KEYSTORE }}
          release-keystore-passphrase: ${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}
          output-directory: /tmp/build/android
        
      - name: Get packages and run codegen
        run: |
          bash /tmp/build/scripts/install_dependencies_with_submodule.sh
          bash /tmp/build/scripts/update_changelogs.sh

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: /tmp/build/android
          
      - name: Build and publish GitHub release
        run: |
          cd /tmp/build/android
          $FLUTTER_ROOT/flutter build appbundle --release
          $FLUTTER_ROOT/flutter build apk --split-per-abi --release
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
